### ISSUE TITLE
Symmetric and asymmetric inputs

### ISSUE THREAD

**Issue by ZhouWenjun2019** [kubota0130/ipc#1]
In `sample2_memory_function.ipynb`, I wonder why the input signal is not uniform in the following codes:
`ipc = single_input_ipc(zeta_sym, Two, degdelays, poly=poly, distr=distr, zerobased=True)`
and
`x[:, t] = np.tanh(rho*w.dot(x[:, t-1]) + iota*win*zeta_asym[t-1])`
Can they be non-uniform? I look forward to your reply !

**Comment by kubota0130** [comment]
Thank you for your question. The input follows a uniform distribution but its range is not symmetric. 
In this notebook, we changed the range of the uniform random input from [-1, 1] to [0, 1] to get the second-order capacities. 
If the input is symmetric, the ESN has only odd-order capacities. So we cannot demonstrate the second-order IPC map.

**Comment by ZhouWenjun2019** [comment]
Sorry, I didn't express myself clearly. I wonder why the IPC use a symmetric uniform input, but the ESN use an asymmetric uniform input.

So, when instantiating an IPC, a symmetric input must be used, but an ESN can use any range of uniformly distributed inputs. Can I understand it this way?

**Comment by kubota0130** [comment]
That's right. 
The IPC requires the uniform input in the range of [-1, 1] to make target polynomials orthogonal. 
If you use [0, 1], the polynomials overlap, leading to a total capacity greater than its upper bound. 
The input range for IPC is strictly determined by the corresponding polynomial. 
On the other hand, the ESN can receive any range of input.

**Comment by ZhouWenjun2019** [comment]
Great thanks for your reply !
